#!/bin/sh
rm -f config.cache
aclocal -I m4
autoconf
autoheader
automake -a
mkdir -p build \
    lib/world/wld/olc \
    lib/world/obj/olc \
    lib/world/mob/olc \
    lib/world/zon/olc \
    lib/log log/parsed \
    lib/bak \
    lib/etc
cp /etc/localtime lib/etc/ # for chroot
