all default: structs.h

structs.h: defs.h obj_data.h constants.h char_data.h desc_data.h room_data.h search.h weather.h zone_data.h ban.h character_list.h
	touch structs.h
character_list.h: safe_list.h
clean depend: FORCE

FORCE:
